Map<String, String> nutrients = {
  "CA": 'Calcium',
  'ENERC_KCAL': 'Energy',
  'CHOCDF': 'Carbs',
  'NIA': 'Niacin (B3)	',
  'CHOLE': 'Cholesterol',
  'P': 'Phosphorus',
  'FAMS': 'Monounsaturated',
  'PROCNT': 'Protein',
  'FAPU': 'Polyunsaturated',
  'RIBF': 'Riboflavin (B2)',
  'FASAT': 'Saturated',
  'SUGAR': 'Sugars',
  'FAT': 'Fat',
  'THIA': 'Thiamin (B1)',
  'FATRN': 'Trans',
  'TOCPHA': 'Vitamin E',
  'FE': 'Iron',
  'VITA_RAE': 'Vitamin A',
  'FIBTG': 'Fiber',
  'VITB12': 'Vitamin B12',
  'FOLDFE': 'Folate (Equivalent)	',
  'VITB6A': 'Vitamin B6',
  'K': 'Potassium',
  'VITC': 'Vitamin C	',
  'MG': 'Magnesium',
  'VITD': 'Vitamin D',
  'NA': 'Sodium',
  'VITK1': 'Vitamin K'
};
